import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 文档侧边栏：包含 docs 根目录下的文档，排除 api 子目录
  tutorialSidebar: [
    'intro',
    'quick-start',
    'markdown-syntax',
    'theme-customization',
    'deployment',
    'changelog',
  ],

  // API 侧边栏
  apiSidebar: [
    {type: 'autogenerated', dirName: 'api'},
  ],

  // 知识侧边栏：docs/konwledge 目录下的文章
  knowledgeSidebar: [
    {type: 'autogenerated', dirName: 'konwledge'},
  ],

  // 笔记侧边栏：从 wujihuan-doc 迁移过来的文档
  // 子目录使用 autogenerated，章节文件按数字顺序（chapter_1 ... chapter_N）自动排序，
  // 标题取自各 markdown 文件的 H1。
  notesSidebar: [
    // ===== AI 系列 =====
    {
      type: 'category',
      label: 'AI 系列',
      collapsed: false,
      items: [
        {type: 'category', label: 'AI Agent 学习', items: [{type: 'autogenerated', dirName: 'handbook/ai-agent'}]},
        {type: 'category', label: 'AI Agent 企业应用实战', items: [{type: 'autogenerated', dirName: 'handbook/ai-agent-dev'}]},
        {type: 'category', label: 'AI Agent 全栈开发', items: [{type: 'autogenerated', dirName: 'handbook/ai-agent-fullstack'}]},
        {type: 'category', label: 'AI 产品经理特训营', items: [{type: 'autogenerated', dirName: 'handbook/ai-agent-product'}]},
        {type: 'category', label: 'AI Agent 原生开发', items: [{type: 'autogenerated', dirName: 'handbook/ai-agent-raw'}]},
        {type: 'category', label: 'AI-SDD 实战', items: [{type: 'autogenerated', dirName: 'handbook/ai-sdd'}]},
        {type: 'category', label: 'AI 提效工具', items: [{type: 'autogenerated', dirName: 'handbook/ai-tools'}]},
        {type: 'category', label: 'AI 多模态生成', items: [{type: 'autogenerated', dirName: 'handbook/ai-multi-image-video'}]},
        {type: 'category', label: 'Agent 面试题', items: [{type: 'autogenerated', dirName: 'handbook/agent-interview'}]},
        {type: 'category', label: 'FDE 角色与职业', items: [{type: 'autogenerated', dirName: 'handbook/agent-fed'}]},
      ],
    },

    // ===== 编程语言 =====
    {
      type: 'category',
      label: '编程语言',
      items: [
        {type: 'category', label: 'Python 学习', items: [{type: 'autogenerated', dirName: 'handbook/python'}]},
        {type: 'category', label: 'Python 实战训练营', items: [{type: 'autogenerated', dirName: 'handbook/python-practice'}]},
        {type: 'category', label: 'Python 高级爬虫', items: [{type: 'autogenerated', dirName: 'handbook/python-crawler'}]},
        {type: 'category', label: 'Python 移动端爬虫', items: [{type: 'autogenerated', dirName: 'handbook/python-mobile-crawler'}]},
        {type: 'category', label: 'LLM 开发实战', items: [{type: 'autogenerated', dirName: 'handbook/python-llm'}]},
        {type: 'category', label: 'GoLang 学习', items: [{type: 'autogenerated', dirName: 'handbook/golang'}]},
        {type: 'category', label: 'Go 实战训练营', items: [{type: 'autogenerated', dirName: 'handbook/go-practice'}]},
        {type: 'category', label: 'Go 专家进阶营', items: [{type: 'autogenerated', dirName: 'handbook/go-expert-course'}]},
      ],
    },

    // ===== 前端框架 =====
    {
      type: 'category',
      label: '前端框架',
      items: [
        {type: 'category', label: 'Next.js 开发实战', items: [{type: 'autogenerated', dirName: 'handbook/nextjs'}]},
        {type: 'category', label: 'React Native 跨端开发', items: [{type: 'autogenerated', dirName: 'handbook/react-native'}]},
      ],
    },

    // ===== 数据库 =====
    {
      type: 'category',
      label: '数据库',
      items: [
        {type: 'category', label: 'MySQL 学习', items: [{type: 'autogenerated', dirName: 'handbook/mysql'}]},
        {type: 'category', label: 'Redis 学习', items: [{type: 'autogenerated', dirName: 'handbook/redis'}]},
      ],
    },

    // ===== 框架与工具 =====
    {
      type: 'category',
      label: '框架与工具',
      items: [
        {type: 'category', label: 'FastAPI 学习', items: [{type: 'autogenerated', dirName: 'handbook/fastapi'}]},
        {type: 'category', label: 'LangChain 学习', items: [{type: 'autogenerated', dirName: 'handbook/langchain'}]},
        {type: 'category', label: 'Electron 学习', items: [{type: 'autogenerated', dirName: 'handbook/electron'}]},
        {type: 'category', label: 'CDP 学习', items: [{type: 'autogenerated', dirName: 'handbook/cdp'}]},
        {type: 'category', label: 'H5 开发', items: [{type: 'autogenerated', dirName: 'handbook/100_h5'}]},
      ],
    },

    // ===== 产品与认知 =====
    {
      type: 'category',
      label: '产品与认知',
      items: [
        {type: 'category', label: '产品经理课', items: [{type: 'autogenerated', dirName: 'handbook/ai-product'}]},
        {type: 'category', label: '认知偏差手册', items: [{type: 'autogenerated', dirName: 'handbook/user-cognition'}]},
        {type: 'category', label: '管理思维模型', items: [{type: 'autogenerated', dirName: 'handbook/100_manage'}]},
      ],
    },

    // ===== 经济学 =====
    {
      type: 'category',
      label: '经济学',
      items: [
        {type: 'category', label: '经济学原理', items: [{type: 'autogenerated', dirName: 'handbook/economic-principles'}]},
      ],
    },

    // ===== 百科知识 =====
    {
      type: 'category',
      label: '百科知识',
      items: [
        {type: 'category', label: 'AI/ML 研究机构', items: [{type: 'autogenerated', dirName: 'handbook/100_academic'}]},
        {type: 'category', label: '科技巨头与平台公司', items: [{type: 'autogenerated', dirName: 'handbook/100_company'}]},
        {type: 'category', label: '科技与互联网先驱', items: [{type: 'autogenerated', dirName: 'handbook/100_people'}]},
        {type: 'category', label: '自然奇观', items: [{type: 'autogenerated', dirName: 'handbook/100_location'}]},
        {type: 'category', label: '哲学与思想', items: [{type: 'autogenerated', dirName: 'handbook/100_book'}]},
      ],
    },

  ],

  // 书籍侧边栏：docs/book 目录下的系列文章
  bookSidebar: [
    {type: 'category', label: '猫的知识全书', items: [{type: 'autogenerated', dirName: 'book/cat'}]},
    {type: 'category', label: '大明通史', items: [{type: 'autogenerated', dirName: 'book/history'}]},
    {type: 'category', label: 'AI 绘画教程', items: [{type: 'autogenerated', dirName: 'book/create-image'}]},
    {type: 'category', label: '英语学习', items: [{type: 'autogenerated', dirName: 'book/english'}]},
    {type: 'category', label: '全村穿越后又穿越回去了', items: [{type: 'autogenerated', dirName: 'book/skill-book/全村穿越后又穿越回去了/正文'}]},
  ],
};

export default sidebars;
