import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 每个大类一个独立 sidebar，只显示该分类下的子目录
  historySidebar: [
    {
      type: 'autogenerated',
      dirName: 'history-humanities',
    },
  ],
  businessSidebar: [
    {
      type: 'autogenerated',
      dirName: 'business-economics',
    },
  ],
  aiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ai-practice',
    },
  ],
  pythonSidebar: [
    {
      type: 'autogenerated',
      dirName: 'python-crawler',
    },
  ],
  backendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'backend-database',
    },
  ],
  frontendSidebar: [
    {
      type: 'autogenerated',
      dirName: 'frontend-engineering',
    },
  ],
  lifeSidebar: [
    {
      type: 'autogenerated',
      dirName: 'life-encyclopedia',
    },
  ],
};

export default sidebars;
