import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 唯一侧边栏：7 大分类，自动生成
  // 每个子目录有 _category_.json 控制标签和折叠状态，
  // index.mdx 作为卡片导航页，点击卡片再进具体文章。
  mainSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
